name: Check Ping Group Range

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-ping-group-range:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Display System Info
        run: |
          echo "OS Version:"
          cat /etc/os-release
          echo "Kernel Version:"
          uname -a

      - name: Check Current Ping Group Range
        run: |
          echo "Current ping_group_range setting:"
          sysctl net.ipv4.ping_group_range || echo "Setting not available"

      - name: Print Ping Group Range from Proc
        run: |
          if [ -f /proc/sys/net/ipv4/ping_group_range ]; then
            echo "Ping group range from /proc/sys/net/ipv4/ping_group_range:"
            cat /proc/sys/net/ipv4/ping_group_range
          else
            echo "Ping group range file does not exist"
          fi

      - name: Test Unprivileged Ping
        run: |
          echo "Testing unprivileged ping to 127.0.0.1..."
          ping -c 1 -W 1 127.0.0.1 || echo "Unprivileged ping failed"
